// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCdSQ6UfzJQEKRBMjrxb_QQdZOYnE4bOY',
    appId: '1:755253626285:web:2743cb87cfa7c8c71d0d24',
    messagingSenderId: '755253626285',
    projectId: 'railwaytracker-7c1a8',
    authDomain: 'railwaytracker-7c1a8.firebaseapp.com',
    storageBucket: 'railwaytracker-7c1a8.firebasestorage.app',
    measurementId: 'G-HPW71PK5MC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUj0UGWrpZCdk-MgQDs3a9BbV9VjsrCwg',
    appId: '1:755253626285:ios:3d01d21771878c851d0d24',
    messagingSenderId: '755253626285',
    projectId: 'railwaytracker-7c1a8',
    storageBucket: 'railwaytracker-7c1a8.firebasestorage.app',
    iosBundleId: 'com.example.railwayTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCdSQ6UfzJQEKRBMjrxb_QQdZOYnE4bOY',
    appId: '1:755253626285:web:0f5a7cf1eee989a51d0d24',
    messagingSenderId: '755253626285',
    projectId: 'railwaytracker-7c1a8',
    authDomain: 'railwaytracker-7c1a8.firebaseapp.com',
    storageBucket: 'railwaytracker-7c1a8.firebasestorage.app',
    measurementId: 'G-X41ZWPLR31',
  );

}